# Generated by Django 5.0.6 on 2024-07-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
